SELECT * FROM blog_management_update.blog;

INSERT INTO `blog_management_update`.`blog` (`content`, `created_day`, `summary`, `category_id`) VALUES ('Đà Nẵng là một thành phố đẹp và hoạt động của Việt Nam, có nhiều điểm tham quan hấp dẫn và các hoạt động giải trí dành cho du khách.', '2023-02-07 00:00:00.000000', 'Du lịch Đà Nẵng', '3');
INSERT INTO `blog_management_update`.`blog` (`content`, `created_day`, `summary`, `category_id`) VALUES ('Trong mỗi trái tim người Việt có một Việt Nam theo cảm nhận của riêng mình, nhưng tôi chắc chắn rằng những cảm xúc ấy sẽ gặp nhau ở lòng yêu Tổ quốc và tinh thần dân tộc. Trong đất nước có tôi và trong tôi có một phần đất nước. Việt Nam trong tôi – đơn giản là dòng máu đỏ tươi đang chảy trong huyết mạch.', '2023-01-11 00:00:00.000000', 'Việt Nam trong tôi là…', '3');
INSERT INTO `blog_management_update`.`blog` (`content`, `created_day`, `summary`, `category_id`) VALUES ('ChatGPT là một mô hình ngôn ngữ sử dụng deep learning, có khả năng tự động hóa các tác vụ về ngôn ngữ như viết văn bản, trả lời câu hỏi, v.v. Các tính năng của ChatGPT bao gồm việc hỗ trợ tạo ra câu trả lời tự nhiên và chính xác cho các câu hỏi của người dùng, việc tự động hoá các tác vụ về xử lý ngôn ngữ, v.v.', '2022-02-11 00:00:00.000000', 'ChatGPT', '2');
INSERT INTO `blog_management_update`.`blog` (`content`, `created_day`, `summary`, `category_id`) VALUES ('Apple Inc. là một công ty công nghệ Mỹ đứng đầu thế giới, được thành lập vào năm 1976 bởi Steve Jobs, Steve Wozniak và Ronald Wayne. Công ty đã trở nên nổi tiếng với sản phẩm đầu tiên là máy tính Apple I. Sau đó, Apple đã phát triển ra nhiều sản phẩm nổi bật như Macintosh, iPod, iPhone và iPad. Hiện nay, Apple là một trong những công ty công nghệ lớn nhất về doanh thu và tài sản trên thế giới.', '2022-01-22 00:00:00.000000', 'Apple Inc.', '2');
INSERT INTO `blog_management_update`.`blog` (`content`, `created_day`, `summary`, `category_id`) VALUES ('Xiaomi là một công ty công nghệ Trung Quốc được thành lập vào năm 2010 bởi Lei Jun. Công ty ban đầu đầu tư vào sản xuất smartphone, nhưng sau đó đã mở rộng ra nhiều lĩnh vực khác như thiết bị điện tử gia dụng, phần mềm và dịch vụ. Xiaomi được biết đến với các sản phẩm có giá cả phải chăng và chất lượng tốt. Trong năm qua, Xiaomi đã trở thành một trong những nhà sản xuất smartphone lớn nhất trên thế giới và đang tiếp tục mở rộng quỹ đầu tư vào nhiều lĩnh vực mới.', '2023-01-01 00:00:00.000000', 'Xiaomi', '2');
INSERT INTO `blog_management_update`.`blog` (`content`, `created_day`, `summary`, `category_id`) VALUES ('Mùa thu tại Hà Nội được coi là mùa đẹp nhất trong năm với những chiếc hoa cẩm chướng đẹp như hoa dại, hoa sen và hoa lụa. Không gian xanh của các khu vườn, công viên và những con sông trong thành phố tạo nên một cảnh tượng đẹp mắt. Ngoài ra, Hà Nội còn có nhiều hoạt động du lịch vào mùa thu như tham quan chùa, đi dạo trong khu phố cổ hoặc tận hưởng một chiều đi xe đạp trong mùa thu.', '2023-01-14 00:00:00.000000', 'Hà Nội mùa thu', '3');
INSERT INTO `blog_management_update`.`blog` (`content`, `created_day`, `summary`, `category_id`) VALUES ('Sau cuộc điều tra kéo dài 4 năm, Ban tổ chức Ngoại hạng Anh thông báo Man City đã vi phạm quy định tài chính rất nhiều lần trong suốt 9 mùa giải. Nếu các cáo buộc được chứng minh, đội bóng thành Manchester có thể đối mặt với án phạt bị trừ điểm như Juventus hoặc thậm chí là bị trục xuất khỏi Liên đoàn.', '2022-12-13', 'Man City bị cáo buộc vi phạm tài chính', '1');
INSERT INTO `blog_management_update`.`blog` (`content`, `created_day`, `summary`, `category_id`) VALUES ('Sau hai cú vấp ngã đau điếng đầu mùa, Man United đã gượng dậy theo cách của mình dù chưa hẳn đã thuyết phục được giới chuyên môn lẫn người hâm mộ. Tuy vậy, tất cả thị phị đã phải nhường chỗ cho những lời ca ngợi từ giới truyền thông Anh, bởi ai cũng hiểu thắng đến trận thứ tư liên tiếp không còn là chuyện may rủi mà phải có năng lực thực sự, hay nói cách khác, Man United đã thực sự hồi sinh dưới tay ông thầy Erik ten Hag.', '2023-02-07', 'Sự hồi sinh của Man United', '1');
